### ISSUE TITLE
🚑 Maps not visible on the staging admin dashboard

### ISSUE THREAD

**Issue by shankari** [e-mission/op-admin-dashboard#110]
https://github.com/e-mission/op-admin-dashboard/assets/2423263/b9c8748d-60d0-463e-8598-9bb364846377

**Comment by shankari** [comment]
Error from the logs:

```
ERROR:app_sidebar_collapsible:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/dash/dash.py", line 1310, in dispatch
    ctx.run(
  File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/dash/_callback.py", line 442, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/usr/src/app/pages/map.py", line 239, in update_user_ids_options
    user_ids_options, user_ids = create_user_ids_options(trips_data['users_data_by_user_id'])
KeyError: 'users_data_by_user_id'
```

**Comment by shankari** [comment]
@jiji14 @achasmita @JGreenlee for visibility
